name: 'Create GH Issue when upstream releases new version'
description: 'Create GH Issue when upstream releases new version'
author: 'Mahesh Rayas'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
  repo:
    description: 'pass github repository'
  days:
    description: 'frequency of scan (must match the cron scheduler)'

runs:
  using: 'docker'
  image: 'docker://maheshrayas/release-notifier:1.0'
branding:
  icon: 'zoom-in'
  color: 'purple'