name: 'Create GH Issue when upstream releases new version'
description: 'Create GH Issue when upstream releases new version'
author: 'Mahesh Rayas'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
  repo:
    description: 'pass github repository or rss feed url'
    required: true
  days:
    description: 'frequency of scan (must match the cron scheduler)'
    default: 1
  type:
    description: 'release type: Github or Rss'
    required: true
  labels:
    description: 'add desired label to GH Issue'

runs:
  using: 'docker'
  image: 'docker://maheshrayas/release-notifier:v2.1'
branding:
  icon: 'zoom-in'
  color: 'purple'